# Generated by Django 4.0.6 on 2023-03-30 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_orderplaced_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='locality',
            new_name='country',
        ),
    ]
